kotlin:
  sourceSets:
    commonMain:
      dependencies:
        - $compose.foundation
        - $compose.material3
    androidMain:
      dependencies:
        - $libs.androidx.activity.compose

compose:
  enabled: true
  resources:
    publicResClass: true
    packageOfResClass: resources
    generateResClass: Auto
