kotlin:
  sourceSets:
    commonMain:
      dependencies:
        - $compose.foundation
        - $compose.material3

compose:
  enabled: true
  resources:
    packageName: resources
    exposedAccessors: true
  experimental:
    hotReload:
      enabled: true
