[versions]
kotlin = "$kotlin"
compose = "$compose"
materialExtendedIcon = "$materialExtendedIcon"

[libraries]
##Common
animation =  { module = "org.jetbrains.compose.animation:animation", version.ref = "compose" }
animationGraphics =  { module = "org.jetbrains.compose.animation:animation-graphics", version.ref = "compose" }
foundation =  { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
material =  { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
material3 =  { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
material3AdaptiveNavigationSuite =  { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "compose" }
runtime =  { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
runtimeSaveable =  { module = "org.jetbrains.compose.runtime:runtime-saveable", version.ref = "compose" }
ui =  { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
uiTest =  { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
uiTooling =  { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
uiUtil =  { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose" }
preview =  { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
materialIconsExtended =  { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialExtendedIcon" }
components-resources =  { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
components-uiToolingPreview =  { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose" }
##Desktop
desktop-common =  { module = "org.jetbrains.compose.desktop:desktop", version.ref = "compose" }
desktop-linux_x64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "compose" }
desktop-linux_arm64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-arm64", version.ref = "compose" }
desktop-windows_x64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "compose" }
desktop-windows_arm64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-arm64", version.ref = "compose" }
desktop-macos_x64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "compose" }
desktop-macos_arm64 =  { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "compose" }
desktop-uiTestJUnit4 =  { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose" }
desktop-currentOs =  { module = "org.jetbrains.compose.desktop:desktop-jvm-$currentTargetId", version.ref = "compose" }
desktop-components-splitPane =  { module = "org.jetbrains.compose.components:components-splitpane", version.ref = "compose" }
desktop-components-animatedImage =  { module = "org.jetbrains.compose.components:components-animatedimage", version.ref = "compose" }
##Web
html-core =  { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
html-svg =  { module = "org.jetbrains.compose.html:html-svg", version.ref = "compose" }
html-testUtils =  { module = "org.jetbrains.compose.html:html-test-utils", version.ref = "compose" }
