ui:
  theme:
    isDynamic: false
    dynamicColorScheme:
      seedColor: 0xFF00FFFF
      animate: true
      animationSpec:
        spring: { }
      contrastLevel: 0
      platform: PHONE
    isAmoled: false
    isHighContrast: false
    isInvert: false
    animate: true
    animationSpec:
      tween:
        durationMillis: 3000
    isExpressive: true
    shapes:
      small:
        squircle:
          topStart:
            dp:
              size: 16
          topEnd:
            dp:
              size: 16
          bottomStart:
            dp:
              size: 16
          bottomEnd:
            dp:
              size: 16
          smoothing: 48
      medium:
        squircle:
          topStart:
            dp:
              size: 32
          topEnd:
            dp:
              size: 32
          bottomStart:
            dp:
              size: 32
          bottomEnd:
            dp:
              size: 32
          smoothing: 48
      large:
        squircle:
          topStart:
            dp:
              size: 100
          topEnd:
            dp:
              size: 100
          bottomStart:
            dp:
              size: 100
          bottomEnd:
            dp:
              size: 100
          smoothing: 48
    typography: { }
