ui:
  startRoute: http://login
  authRoute: http://login
  authRedirectRoute: http://localhost/services
  routes:
    authentification:
      isAuth: true
    phone:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    totp:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    hotp:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    pin_code:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    reset_pin_code:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    login:
      isAuth: true
      additionalMetadata:
        topAppBarNavSuite: true
    home:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    news:
      authResource: { }
    articles:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    article_details:
      additionalMetadata:
        navSuite: true
      authResource: { }
    map:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    services:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    wallet:
      authResource: { }
    balance:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    crypto:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    exchange:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    profile:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    verification:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    about:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings:
      authResource: { }
    settings_main:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_color_scheme:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_dynamic_color_scheme:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_shapes:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_typography:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_route:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    support:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }



