validator:
  user:
    username:
      rules:
        - pattern: '[\s\S]+'
          message: value_is_empty
    first-name:
      rules:
        - pattern: '[\s\S]+'
          message: value_is_empty
    last-name:
      rules:
        - pattern: '[\s\S]+'
          message: value_is_empty
    phone:
      rules:
        - pattern: '[\s\S]+'
          message: value_is_empty
        - pattern: '[\s\S]{3,15}'
          message: value_length_is_incorrect
        - pattern: '^\+[\s\S]*'
          message: value_prefix_is_incorrect
        - pattern: '[\s\S]*\d+[\s\S]*'
          message: value_has_no_digits
        - pattern: '[^A-ZА-Яa-zа-я]*'
          message: value_has_letters
        - pattern: '\+(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\d{1,14}$'
          message: value_is_incorrect
      required: false
    email:
      rules:
        - pattern: '[\s\S]+'
          message: value_is_empty
        - pattern: '[\s\S]{3,256}'
          message: value_length_is_incorrect
        - pattern: '[^ ]*'
          message: value_has_whitespace
        - pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          message: value_is_incorrect
