auth:
  otp:
    totp:
      period: PT60S
      codeDigits: 4
      hmacAlgorithm: sha512
  google:
    webClientId: 444505512670-rtg2r4ikm8squut505ep1gqnqae5nmbr.apps.googleusercontent.com
    clientSecret: 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
  supabase:
    config:
      supabaseUrl: https://tjtexgktpxmahfoiiehr.supabase.co
      supabaseKey: sb_publishable_upFvLGSLpb_HQU7TKjKoSg_Tn5Funjc
      deepLinkHost: localhost
      deepLinkScheme: https
    redirectUrl: https://localhost/services
  supabaseOAuths:
    - provider: GITHUB
      config: { }
    - provider: TWITTER
      config: { }
    - provider: AZURE
      config: { }
    - provider: KEYCLOAK
      config: { }
