ui:
  startRoute: auth
  authRoute: auth
  authRedirectRoute: news
  routes:
    phone:
      metadata:
        topAppBarNavSuite: true
    totp:
      metadata:
        topAppBarNavSuite: true
    hotp:
      metadata:
        topAppBarNavSuite: true
    pin_code:
      metadata:
        topAppBarNavSuite: true
    forgot_pin_code:
      metadata:
        topAppBarNavSuite: true
    login:
      metadata:
        topAppBarNavSuite: true
    home:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    articles:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    article_details:
      metadata:
        navSuite: true
      authResource: { }
    map:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    services:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    balance:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    crypto:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    stock:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    profile:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    verification:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    about:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_main:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_color_scheme:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_dynamic_color_scheme:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_shapes:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_typography:
      metadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_route:
      metadata:
        topAppBarNavSuite: true
      authResource: { }



