localization:
  locales:
    - en-US
    - ru-RU
    - tg-TJ
  locale: en-US
  weblates:
    - enable: true
      baseUrl: http://localhost:8090
      projectName: application
      apiKey: wlu_aiwHaV8hd99eJeHgc5LPznz20croHxo2C22z
