ui:
  theme:
    isDynamic: false
    isHighContrast: false
    isExpressive: true
    dynamicColorScheme:
      seedColor: 0xFF00FFFF
      animate: true
      animationSpec:
        spring: { }
    dynamicColorSchemeHighContrast:
      seedColor: 0xFF0000FF
      amoled: true
    animate: true
    animationSpec:
      tween:
        durationMillis: 3000
    shapes:
      small:
        squircle:
          topStart:
            dp:
              size: 16
          topEnd:
            dp:
              size: 16
          bottomStart:
            dp:
              size: 16
          bottomEnd:
            dp:
              size: 16
          smoothing: 48
      medium:
        squircle:
          topStart:
            dp:
              size: 32
          topEnd:
            dp:
              size: 32
          bottomStart:
            dp:
              size: 32
          bottomEnd:
            dp:
              size: 32
          smoothing: 48
      large:
        squircle:
          topStart:
            dp:
              size: 100
          topEnd:
            dp:
              size: 100
          bottomStart:
            dp:
              size: 100
          bottomEnd:
            dp:
              size: 100
          smoothing: 48
    typography: { }
