localization:
  locales:
    - en-US
    - ru-RU
    - tg-TJ
  locale: en-US
  weblate:
    app:
      enable: true
      baseUrl: 'http://localhost:8090'
      api-key: wlu_aiwHaV8hd99eJeHgc5LPznz20croHxo2C22z
