ui:
  startRoute: auth
  authRoute: auth
  authRedirectRoute: services
  routes:
    phone:
      additionalMetadata:
        topAppBarNavSuite: true
    totp:
      additionalMetadata:
        topAppBarNavSuite: true
    hotp:
      additionalMetadata:
        topAppBarNavSuite: true
    pin_code:
      additionalMetadata:
        topAppBarNavSuite: true
    reset_pin_code:
      additionalMetadata:
        topAppBarNavSuite: true
    login:
      additionalMetadata:
        topAppBarNavSuite: true
    home:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    articles:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    article_details:
      additionalMetadata:
        navSuite: true
      authResource: { }
    map:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    services:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    balance:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    crypto:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    exchange:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    profile:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    verification:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    about:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_main:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_color_scheme:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_dynamic_color_scheme:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_shapes:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_typography:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }
    settings_route:
      additionalMetadata:
        topAppBarNavSuite: true
      authResource: { }



