ui:
  theme:
    isDynamic: true
    isHighContrast: true
    isExpressive: true
    dynamicColorPalette:
      seedColor: 4278255615
      animate: true
      animationSpec:
        spring: { }
    dynamicColorPaletteHighContrast:
      seedColor: 4278190335
      animate: true
      animationSpec:
        spring: { }
    shapes:
      small:
        squircle:
          topStart:
            dp:
              size: 16
          topEnd:
            dp:
              size: 16
          bottomStart:
            dp:
              size: 16
          bottomEnd:
            dp:
              size: 16
          smoothing: 48
      medium:
        squircle:
          topStart:
            dp:
              size: 32
          topEnd:
            dp:
              size: 32
          bottomStart:
            dp:
              size: 32
          bottomEnd:
            dp:
              size: 32
          smoothing: 48
      large:
        squircle:
          topStart:
            dp:
              size: 100
          topEnd:
            dp:
              size: 100
          bottomStart:
            dp:
              size: 100
          bottomEnd:
            dp:
              size: 100
          smoothing: 48
    typography: { }

