imports:
  - application-log.yaml
  - application-localization.yaml
  - application-validators.yaml
  - application-auth.yaml
  - application-ui-components.yaml
  - application-ui-theme.yaml
  - application-ui-density.yaml
  - application-ui-routes.yaml
