[versions]
# Compose core.
compose = "1.10.0-beta01"
compose-material3 = "1.10.0-alpha04"
compose-material3-adaptive = "1.3.0-alpha01"
compose-material3-adaptive-navigation-suite = "1.10.0-alpha04"
compose-material-icons-extended = "1.7.3"
window-core = "1.5.0-rc01"

[libraries]
# Compose core.
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-material3-adaptive" }
material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "compose-material3-adaptive-navigation-suite" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
window-core = { module = "org.jetbrains.androidx.window:window-core", version.ref = "window-core" }
# HTML/JS target.
html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
# UI tooling.
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
# testing.
ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
