config:
  imports:
    - java.net.URI
    - java.util.Date
    - org.gradle.kotlin.dsl.*
    - org.gradle.api.JavaVersion
    - org.gradle.jvm.toolchain.JavaLanguageVersion
    - org.jetbrains.kotlin.gradle.dsl.JvmTarget
    - gradle.plugins.kotlin.targets.jvm.toJvmTarget
  jvmTarget: 22
  compilerOptions:
    - -Xignore-const-optimization-errors
    - -Xinline-classes
    - -Xwhen-guards
    - -Xnon-local-break-continue
    - -Xcontext-parameters
    - -Xmulti-dollar-interpolation
    - -Xrender-internal-diagnostic-names
