config:
  imports:
    - java.net.URI
    - java.util.Date
    - org.gradle.kotlin.dsl.*
    - org.gradle.api.JavaVersion
    - org.gradle.jvm.toolchain.JavaLanguageVersion
    - org.gradle.jvm.toolchain.JvmVendorSpec
    - org.jetbrains.kotlin.gradle.dsl.JvmTarget
    - org.jetbrains.kotlin.gradle.dsl.KotlinVersion
    - org.jetbrains.kotlin.gradle.tasks.KotlinCompile
    - org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
    - org.gradle.api.file.DuplicatesStrategy
    - gradle.api.kotlin.targets.jvm.toJvmTarget
  jvmTarget: 22
  compilerOptions:
    - -Xignore-const-optimization-errors
    - -Xinline-classes
    - -Xwhen-guards
    - -Xnon-local-break-continue
    - -Xcontext-parameters
    - -Xmulti-dollar-interpolation
    - -Xrender-internal-diagnostic-names
