config:
  imports:
    - io.ktor.server.plugins.swagger.swaggerUI
script:
  - module: |
      {
        routing {
          // Expose Swagger UI using OpenAPI specification at documentation file.
          swaggerUI("swagger", "openapi/documentation.yaml") {
            // Add configuration for this Swagger UI "instance" here.
          }

          route("swagger") {
            // Expose Swagger UI using OpenAPI specification at `/api.yaml`.
            // Path can be relative pointing to specification provided by this application or absolute pointing to an external resource.
            io.github.smiley4.ktorswaggerui.swaggerUI("/api.yaml") {
              // Add configuration for this Swagger UI "instance" here.
            }
          }
        }
      }
