script:
  - module: |
      {
        install(RoutingRoot) {
          staticFiles(
            remotePath = "/",
            dir = File("files"),
          ) {
            preCompressed(
                CompressedFileType.BROTLI,
                CompressedFileType.GZIP,
            )
            enableAutoHeadResponse()
          }

          staticResources(
            remotePath = "/",
            basePackage = "static",
          ) {
            default("static/index.html")
            preCompressed(
                CompressedFileType.BROTLI,
                CompressedFileType.GZIP,
            )
            enableAutoHeadResponse()
          }
        }
      }
