config:
  imports:
    - io.ktor.server.plugins.swagger.swaggerUI
script:
  - module: |
      {
        routing {
          swaggerUI(path = "swagger", swaggerFile = "openapi/documentation.yaml")
        }
      }
