micrometer-metrics:
  enable: true
  type: PROMETHEUS
  class-loader-metrics: true
  jvm-memory-metrics: true
  jvm-gc-metrics: true
  processor-metrics: true
  jvm-thread-metrics: true
  file-descriptor-metrics: true
  distribution-statistics:
    enable: true
    percentilesHistogram: true
    maximumExpectedValue: 20s
    serviceLevelObjectives: [ 100ms, 500ms ]
