config:
  imports:
    - io.ktor.server.plugins.calllogging.CallLogging
script:
  - module: |
      {
        install(CallLogging) {
          level = Level.INFO
          filter { call -> true }
        }
      }
