script:
  - module: |
      {
        install(RoutingRoot) {
          staticResources("/", "static") {
            preCompressed(
                CompressedFileType.BROTLI,
                CompressedFileType.GZIP,
            )
            enableAutoHeadResponse()
          }
        }
      }
