config:
  imports:
    - io.ktor.server.plugins.calllogging.CallLogging
    - org.slf4j.event.Level
script:
  - module: |
      {
        install(CallLogging) {
          level = Level.INFO
          filter { call -> true }
        }
      }
