config:
  imports:
    - io.ktor.server.plugins.swagger.swaggerUI
script:
  - module: |
      {
        routing {
          swaggerUI(openApiUrl = "/api.yaml") {
              deepLinking = true
              docExpansion = "none"
          }
        }
      }
