config:
  imports:
    - io.ktor.server.plugins.methodoverride.XHttpMethodOverride
script:
  - module: |
      {
        install(XHttpMethodOverride) {
          headerName = "X-HTTP-Method-Override"
        }
      }
