config:
  imports:
    - org.koin.core.KoinApplication
    - org.koin.ktor.plugin.Koin
    - org.koin.logger.slf4jLogger
    - org.koin.dsl.module
script:
  - module: |
      {
        install(Koin) {
          slf4jLogger(org.koin.core.logger.Level.INFO)
        }
      }
