config:
  imports:
    - io.ktor.server.engine.ShutDownUrl
script:
  - module: |
      {
        install(ShutDownUrl.ApplicationCallPlugin) {
          shutDownUrl = "/shutdown"
          exitCodeSupplier = { 0 }
        }
      }
