localization:
  locales:
    - en-US
    - ru-RU
    - tg-TJ
  locale: en-US
  weblates:
    - enable: true
      baseUrl:  https://hosted.weblate.org/api/
      projectName: weblate
      apiKey: wlu_1HJuwshoOcebcB2KMN10U8Yl7n4HgPkyO5q6
