config:
  imports:
    - io.ktor.server.plugins.defaultheaders.DefaultHeaders
script:
  - module: |
      {
        install(DefaultHeaders) {
          header(HttpHeaders.ETag, UUID.randomUUID().toString())
          header(HttpHeaders.Server, this@module.environment::class.simpleName ?: "KtorServer")
          header("X-Powered-By", "Ktor")
        }
      }
