config:
  imports:
    - io.ktor.server.plugins.httpsredirect.HttpsRedirect
script:
  - module: |
      {
        install(HttpsRedirect) {
          sslPort = applicationScript.server.sslPort
          permanentRedirect = true
        }
      }
