config:
  imports:
    - io.ktor.server.plugins.requestvalidation.RequestValidation
    - io.ktor.server.plugins.requestvalidation.ValidationResult
script:
  - module: |
      {
        install(RequestValidation) {

        }
      }
