config:
  imports:
    - io.ktor.server.plugins.swagger.swaggerUI
    - io.github.smiley4.ktorswaggerui.swaggerUI
script:
  - module: |
      {
        routing {
          // Expose Swagger UI using OpenAPI specification at documentation file.
          swaggerUI("swagger/file", "openapi/documentation.yaml") {
            // Add configuration for this Swagger UI "instance" here.
          }

          route("swagger/api") {
            // Expose Swagger UI using OpenAPI specification at `/openapi/api.yaml`.
            // Path can be relative pointing to specification provided by this application or absolute pointing to an external resource.
            swaggerUI("/openapi/api.yaml") {
              // Add configuration for this Swagger UI "instance" here.
            }
          }
        }
      }
