config:
  imports:
    - io.github.smiley4.ktorswaggerui.swaggerUI
script:
  - module: |
      {
        routing {
          route("swagger") {
            // Expose Swagger UI using OpenAPI specification at `/api.yaml`.
            // Path can be relative pointing to specification provided by this application or absolute pointing to an external resource.
            swaggerUI("/api.yaml") {
              // Add configuration for this Swagger UI "instance" here.
            }
          }
        }
      }
