config:
  imports:
    - io.ktor.server.plugins.compression.Compression
    - io.ktor.server.plugins.compression.gzip
    - io.ktor.server.plugins.compression.minimumSize
script:
  - module: |
      {
        install(Compression) {
          gzip {
              priority = 1.0
              minimumSize(200L)
          }
        }
      }
