config:
  imports:
    - com.apurebase.kgraphql.GraphQL
script:
  - module: |
      {
        install(GraphQL) {
          schema {
            playground = true
            endpoint = "/graphql"
          }
        }
      }
